### ISSUE TITLE
API Error Handling - Add an error handling system that respect REST constraints

### ISSUE THREAD

**Issue by ffouillet** [ffouillet/RESTful_API_BileMo#12]
We will have to create a system that can show API errors respecting REST constraints.
If an Exception get thrown, the API must return a JSON Object containing the HTTP_STATUS_CODE and the error message. Like following : 
```
{
  "code": 404,
  "message": "Ressource not found"
}
```
For that we will need :
- an EventListener on the Symfony **kernel.exception** event. This listener will be in charge of calling the required service depending on the Exception type thrown (see next).
- a tagged Service per type of Exception we want to handle. The tag will always be the same because it will be required by the compiler pass (see next) [tag will be : **core.exception_normalizer**]. In order to be able to handle multiple type of exceptions, we will make sure that the code is open to extension (by using an interface and an abstract class that Services will extend)
- a Compiler pass that will store each tagged Service (with **core.exception_normalizer**) inside the listener so that it can get Exception Information returned by the service then serialized it for the response.

### Tasks : 
- [x] Create the first Service on a reusable code base. This first Service will handle _Symfony\Component\HttpKernel\Exception\NotFoundHttpException_. Other Services for handling 
other types of exception won't require that this Service or the code base have to be modified.
- [x] Register the service in CoreBundle configuration and tag it with **core.exception_normalizer**
- [x] Create the Event Listener that will call our services (the event listener will listen for kernel.exception event).
- [x] Register the listener in CoreBundle configuration
- [x] Create the CompilerPass (in a DependencyInjection directory that will be created in the CoreBundle directory). The compiler pass will grab service whose tag is **core.exception_normalizer** and inject them in a normalizer attribute of the EventListener
- [x] Declare the newly created CompilerPass in the CoreBundle class

Exception types to handle
- [x] NotFoundHTTPException
- [x] ResourceValidationException (create this class)
